---

- hosts: qa
  sudo: yes

  tasks:
  - name: Pull docker image
    shell: docker pull nir16r/spring-petclinic:v1

  - name: Stop docker container
    shell: docker rm -f spring-petclinic

  - name: Run docker container
    shell: docker run -itd -p 8080:8080 --name spring-petclinic nir16r/spring-petclinic:v1


- hosts: prod
  sudo: yes

  tasks:
  - name: Start kubernetes service
    shell: "kubectl apply -f /home/devopsinfra/Service.yaml"
  - name: Start kubernetes deployment
    shell: kubectl apply -f /home/devopsinfra/Deployment.yaml
