---
- hosts: qa
  sudo: yes

  tasks:
    - name: Pull docker image
      shell: docker pull nir16r/spring-petclinic:{{version}}

    - name: Stop docker container
      shell: docker rm -f spring-petclinic

    - name: Run docker container
      shell: docker run -itd -p 8080:8080 --name spring-petclinic nir16r/spring-petclinic:{{version}}

- hosts: prod

  tasks:
    - name: Copy deployment file to Kube Master
      copy: src='Deployment.yaml' dest='~/Deployment.yaml'
    # - name: Start kubernetes service
    #   shell: "kubectl apply -f ~/Service.yaml"
    - name: Rollout kubernetes deployment
      shell: "kubectl --record deployment/spring-petclinic set image deployment/spring-petclinic spring-petclinic=nir16r/spring-petclinic:{{version}}"
      # shell: kubectl apply -f ~/Deployment.yaml
